### ISSUE TITLE
Allow users to DM the bot

### ISSUE THREAD

**Issue by YuriRomanowski** [serokell/tzbot#31]
# Clarification and motivation

Currently it's not possible to send a direct message to the bot, but for this only some extra permissions should be added to the manifest.
Also, even if the user is allowed to DM the bot, the bot won't process this message, although it could. For example, user may want to translate some time references to another time zone.

# Acceptance criteria

* User can send a direct message to the bot and get time references translation if there are any.

**Comment by Martoon-00** [comment]
Cool suggestion :+1:
