### ISSUE TITLE
Add options parsing and default config dump

### ISSUE THREAD

**Issue by YuriRomanowski** [serokell/tzbot#32]
# Clarification and motivation

Currently the bot only takes one optional argument - config filename. But we should have some library that whould treat this in a better way, provide help and program description.
Also, like in [xrefcheck](https://github.com/serokell/xrefcheck) we can add a command `dump-config`.

# Acceptance criteria
* Add options parsing using `optparse-applicative`
* Add `dump-config` command for emiting default configuration with all explaining commentaries.

**Comment by Martoon-00** [comment]
Hmm, I guess it is not part of the initial requirements, and we can live without this, at least until release.

However if we one day get to implementing it, I again remind about [`loot-config`](https://github.com/serokell/lootbox/tree/master/code/config) which allows combining CLI options / yaml / env vars natively, or maybe we should check DHall again. Or extending the current solution is also fine if that can be done in a simple manner.

**Comment by Martoon-00** [comment]
Ah wait, you implemented a PR just a couple of hours ago, nice then :sweat_smile:
