### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by YuriRomanowski** [serokell/tzbot#33]
# Clarification and motivation

Currently in fact there is no normal logging, just slightly modified `putStrLn` is used. I think we should introduce some logging library that meets all the requirements of good logging system.

# Acceptance criteria
* Choose the good logging library
* Replace `print`s with this logging

**Comment by Martoon-00** [comment]
Btw, I just noticed `Slacker.SocketMode` uses some logging, maybe it's logging assumed for Slack Apps :thinking:

**Comment by YuriRomanowski** [comment]
@Martoon-00 Do you have any ideas how the logging should be performed in our case? There are really a lot of logging libraries, and I'm going to go through them and try to compare them and pick the most suitable, but maybe you as more experienced person have a reasonable suggestions?

**Comment by Martoon-00** [comment]
Uhm, I'm pleased that you're asking, but actually, it's a topic where I mostly never had a chance to make a selection myself, nor I got fully satisfied with the solutions I managed to use.

Probably among those that are notable of mention: Serokell once developed [`loot-log`](https://github.com/serokell/lootbox/tree/master/code/log), and I once liked `katip`.

But if you have a desire and motivation to explore the area of existing libraries in the ecosystem, please go for it. I would be interested to see the solution you pick and apply here.

**Comment by YuriRomanowski** [comment]
@Martoon-00 I have just noticed your message and before I picked `katip` rather arbitrarily, it seems that it's OK, maybe because we currently don't have big requirements, but I'm going to look at other libraries more closely in the near future.

**Comment by Martoon-00** [comment]
Cool ))

My impression was that its flexibility is also one of the best among the libraries, but again would be glad to see if you find anything better.
