### ISSUE TITLE
Fix a bunch of issues

### ISSUE THREAD

**Issue by Martoon-00** [serokell/tzbot#44]
# Clarification and motivation

I posted a few issues in [this Notion document](https://www.notion.so/serokell/Testing-iteration-1-from-dbfd12f048824fd68057f664fead248f), let's resolve them under this ticket.

# Acceptance criteria

* All the mentioned issues are discussed and resolved.

**Comment by YuriRomanowski** [comment]
> Each message of bot ends with “Something wrong?” and a button

Indeed, we can just remove it. Instead, we can attempt to give a hint how to use the entrypoints. For example, we can handle `/tzhelp` command and repond with an ephemeral containing help message that contains all the information about how the bot works and what are available entrypoints. But the user should also notice the command existense somehow, and this is what we can write in a simple ephemeral containing the translations. For it not to be too annoying, we can append this not to every ephemeral but for example with 0.1 chance (or less).
