### ISSUE TITLE
Revise exceptions handling

### ISSUE THREAD

**Issue by YuriRomanowski** [serokell/tzbot#51]
# Clarification and motivation

Currently we use `ExceptT BotException IO`, which is not really convenient because we need to handle `BotException` and other possible exceptions from IO separately; this is also considered by an anti-pattern by some folks (https://www.fpcomplete.com/blog/2016/11/exceptions-best-practices-haskell/). I think we should replace this by something else.

# Acceptance criteria

* Discuss how to change our way of exception handling
* Implement the solution

**Comment by Martoon-00** [comment]
I suppose the solution suggested by our guides in the current realms: when working in `IO`, use `BotException` via mere `throw`/`catch` from `universum`. And when need to handle it - just remember that we have special exceptions that we expect in the first place.

But I really don't like this much, and when working on backends I many times regretted we have no mechanism to remember in types which exceptions we expect in the first place.
