### ISSUE TITLE
Use user-friendly language in `/tzhelp`

### ISSUE THREAD

**Issue by dcastro** [serokell/tzbot#65]
# Clarification and motivation

At the moment, the `/tzhelp` command displays the following text:

> Hello!
> I am tzbot - the time zone bot.
> I can capture time references inside messages and translate them to your time zone. Whenever the message is posted in the channel I'm in, if this message contains any time references, I will translate them and send it to you via an ephemeral message. If a time reference is invalid for some reason, I will say what's wrong with it.
> Also you can trigger the message translation yourself, by using entrypoints in the Slack message context menu; this works in every channel of the workspace (including direct messages). There you also can report the bot working wrongly, we will be very grateful for your feedback!

This text uses several terms that regular Slack users (and especially non-programmers) are not familiar with, and thus may be very confusing. For example, "ephemeral message", "entrypoints", and even "context menu". We should avoid using them when possible, or use equivalent terms.

In order to explain what the "context menu" is to users, a bit of visual aid might be helpful. 
We could use the vertical ellipsis unicode symbol, formatted as inline code, i.e.: `⋮`. It seems to have [good font support](https://www.fileformat.info/info/unicode/char/22EE/fontsupport.htm), so it should be rendered correctly on most devices.
(Sidenote: ideally, we would use `<kbd>` html tag, but Slack doesn't support html formatted messages :/ )

Anyway, here's what I propose:

> Hello!
> I am tzbot - the time zone bot.
>
> Invite me to a channel and whenever a message with time references such as "Let's meet at 10am" is posted, I will convert them to your time zone.
> If a time reference is invalid for some reason, I will tell you why and how to fix it.
> 
> You can also manually ask me to translate time references by opening the context menu `⋮` next to a message and selecting "Translate time refs".
> This works in all channels of the workspace, including direct messages.
> 
> Finally, you can use the context menu `⋮` to report any issue with the bot. Your feedback is greatly appreciated!

# Acceptance criteria

* The `/tzhelp` message uses user-friendly language

**Comment by YuriRomanowski** [comment]
You are right, and I like your variation. Let's do it this way!
