### ISSUE TITLE
Raise the limit of the `conversation.members` endpoint

### ISSUE THREAD

**Issue by dcastro** [serokell/tzbot#9]
# Clarification and motivation

Right now, we're not setting the `limit` query param when calling the `conversation.members` Slack endpoint. It defaults to 100.

The [docs](https://api.slack.com/docs/pagination) say: 

> * The limit parameter sets a maximum number of results to return per call.
> * Provide sensible limit values. We recommend 100-200 results at a time.
> * The limit parameter maximum is 1000 and subject to change and may vary per method.

Let's follow the recommendation and add the the `limit` query param to the servant API and set it to 200 when invoking it.

# Acceptance criteria

* The servant API has a `limit` query param
* We're setting it to 200 when invoking it

**Comment by pasqu4le** [comment]
Solved by #10
